TRUNCATE TABLE ADMIN;
TRUNCATE TABLE COURSES;
TRUNCATE TABLE QUESTIONS;
TRUNCATE TABLE ANSWERS;
TRUNCATE TABLE QUIZ_QUESTIONS;
TRUNCATE TABLE QUIZ_ANSWERS;
TRUNCATE TABLE QUIZ_CORRECT;
TRUNCATE TABLE GRADEBOOK;

INSERT INTO COURSES (NAME, BLURB) VALUES ("PHISHING AND SPAMMING",
    "DO YOU HEAR THE PEOPLE SING / SINGING THE SONG OF ANGRY MEN / IT IS THE
    MUSIC OF A PEOPLE WHO WILL NOT BE SLAVES AGAIN / WHEN THE BEATING OF YOUR 
    HEART ECHOES THE BEATING OF THE DRUMS / THERE IS A LIFE ABOUT TO START / 
    WHEN TOMORROW COMES");
INSERT INTO COURSES (NAME, BLURB) VALUES ("SOCIAL ENGINEERING", 
    "YOU AT THE BARRICADE LISTEN TO THIS / NO ONE IS COMING TO HELP YOU FIGHT /
     YOU'RE ON YOUR OWN / YOU HAVE NO FRIENDS / GIVE UP YOUR GUNS / OR DIE");
INSERT INTO COURSES (NAME, BLURB) VALUES ("HOW TO CHOOSE A PASSWORD",
    "WILL YOU JOIN IN OUR CRUSADE / WHO WILL BE STRONG AND STAND WITH ME / 
    SOMEWHERE BEYOND THE BARRICADE IS THERE A WORLD YOU LONG TO SEE / DO YOU 
    HEAR THE PEOPLE SING / SAY DO YOU HEAR THE DISTANT DRUMS / IT IS THE 
    FUTURE THAT WE BRING WHEN TOMORROW COMES");
