DROP DATABASE auscats;
CREATE DATABASE auscats;
USE auscats;
CREATE TABLE ADMIN (USERID VARCHAR(8) NOT NULL,
    NAME VARCHAR(100),
    ORG_UNIT VARCHAR(100),
    PRIMARY KEY (USERID));

CREATE TABLE ADMIN_PERM (USERID VARCHAR(8) NOT NULL,
    PERMISSION VARCHAR(50) NOT NULL,
    PRIMARY KEY(USERID));

CREATE TABLE MODULES (MID INT(6) UNSIGNED NOT NULL AUTO_INCREMENT, 
    STATUS VARCHAR(10) NOT NULL,
    NAME VARCHAR(50) NOT NULL, 
    BLURB VARCHAR(500) NOT NULL, 
    LAST_MODIFIED DATETIME(6),
    PRIMARY KEY(MID), 
    UNIQUE KEY module (NAME));

CREATE TABLE MODULE_CONTENT (MODULE INT(6) UNSIGNED NOT NULL, 
    REVISION INT(6) UNSIGNED NOT NULL, 
    CONTENT BLOB, 
    FOREIGN KEY (MODULE) REFERENCES MODULES (MID) 
    ON UPDATE NO ACTION ON DELETE NO ACTION);

CREATE TABLE QUIZ_QUESTIONS (MODULE INT(6) UNSIGNED NOT NULL,
    QID INT(6) UNSIGNED NOT NULL AUTO_INCREMENT,
    QUESTION VARCHAR(200) NOT NULL, 
    PRIMARY KEY(QID),
    FOREIGN KEY (MODULE) REFERENCES MODULES (MID) 
    ON UPDATE NO ACTION ON DELETE NO ACTION);

CREATE TABLE QUIZ_ANSWERS (QUESTION INT(6) UNSIGNED NOT NULL,
    AID INT(6) UNSIGNED NOT NULL AUTO_INCREMENT,
    ANSWER VARCHAR(200) NOT NULL,
    PRIMARY KEY(AID),
    FOREIGN KEY (QUESTION) REFERENCES QUIZ_QUESTIONS (QID)
    ON UPDATE NO ACTION ON DELETE NO ACTION);

CREATE TABLE CORRECT_ANSWERS (QUESTION INT(6) UNSIGNED NOT NULL,
    ANSWER INT(6) UNSIGNED NOT NULL,
    FOREIGN KEY (QUESTION) REFERENCES QUIZ_QUESTIONS (QID)
    ON UPDATE NO ACTION ON DELETE NO ACTION,
    FOREIGN KEY (ANSWER) REFERENCES QUIZ_ANSWERS (AID)
    ON UPDATE NO ACTION ON DELETE NO ACTION);

CREATE TABLE USER_PROGRESS (USERID VARCHAR(8) NOT NULL,
    MODULE INT(6) UNSIGNED NOT NULL,
    LAST_VIEWED INT(2) UNSIGNED NOT NULL,
    FOREIGN KEY (MODULE) REFERENCES MODULES (MID)
    ON UPDATE NO ACTION ON DELETE NO ACTION);

CREATE TABLE GRADEBOOK (USERID VARCHAR (8) NOT NULL,
    ORG_UNIT VARCHAR(50) NOT NULL,
    QUESTION INT(6) UNSIGNED NOT NULL,
    ANSWER INT(6) UNSIGNED NOT NULL,
    FOREIGN KEY (QUESTION) REFERENCES QUIZ_QUESTIONS (QID)
    ON UPDATE NO ACTION ON DELETE NO ACTION,
    FOREIGN KEY (ANSWER) REFERENCES QUIZ_ANSWERS (AID)
    ON UPDATE NO ACTION ON DELETE NO ACTION);

CREATE VIEW vw_USER_CORRECT_ANSWERS AS
    select USERID, ORG_UNIT, q.MODULE, g.QUESTION, g.ANSWER
    FROM GRADEBOOK g, QUIZ_QUESTIONS q 
    WHERE g.question = q.qid 
    AND g.answer IN (SELECT answer from CORRECT_ANSWERS) 
    group by q.MODULE, g.QUESTION;
