DROP TABLE auscats.ADMIN;
DROP TABLE auscats.COURSES;
DROP TABLE auscats.QUESTIONS;
DROP TABLE auscats.ANSWERS;
DROP TABLE auscats.QUIZ_QUESTIONS;
DROP TABLE auscats.QUIZ_ANSWERS;
DROP TABLE auscats.QUIZ_CORRECT;
DROP TABLE auscats.GRADEBOOK;
CREATE DATABASE auscats;
USE auscats;
CREATE TABLE ADMIN (USERID VARCHAR(8) NOT NULL,
    PRIMARY KEY (USERID));
CREATE TABLE COURSES (CID INT(6) UNSIGNED NOT NULL AUTO_INCREMENT, 
    CODE VARCHAR(10) NOT NULL, 
    BLURB VARCHAR(200) NOT NULL, 
    CONTENT BLOB, 
    PRIMARY KEY(CID), 
    UNIQUE KEY course (CODE));
CREATE TABLE QUESTIONS (QID INT(3) UNSIGNED NOT NULL AUTO_INCREMENT, 
    QUESTION VARCHAR(200) NOT NULL, 
    PRIMARY KEY(QID));
CREATE TABLE ANSWERS (AID INT(6) UNSIGNED NOT NULL AUTO_INCREMENT, 
    ANSWER VARCHAR(200) NOT NULL,
    PRIMARY KEY(AID));
CREATE TABLE QUIZ_QUESTIONS (COURSE INT(6) UNSIGNED NOT NULL,
    QUESTION INT(6) UNSIGNED NOT NULL,
    FOREIGN KEY (COURSE) REFERENCES COURSES (CID) 
    ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (QUESTION) REFERENCES QUESTIONS (QID) 
    ON UPDATE CASCADE ON DELETE CASCADE);
CREATE TABLE QUIZ_ANSWERS (QUESTION INT(6) UNSIGNED NOT NULL,
    ANSWER INT(6) UNSIGNED NOT NULL,
    FOREIGN KEY (QUESTION) REFERENCES QUESTIONS (QID)
    ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (ANSWER) REFERENCES ANSWERS (AID)
    ON UPDATE CASCADE ON DELETE CASCADE);
CREATE TABLE QUIZ_CORRECT (QUESTION INT(6) UNSIGNED NOT NULL,
    ANSWER INT(6) UNSIGNED NOT NULL,
    FOREIGN KEY (QUESTION) REFERENCES QUESTIONS (QID)
    ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (ANSWER) REFERENCES ANSWERS (AID)
    ON UPDATE CASCADE ON DELETE CASCADE);
CREATE TABLE GRADEBOOK (USERID VARCHAR (8) NOT NULL,
    ORGUNIT VARCHAR(50) NOT NULL,
    QUESTION INT(6) UNSIGNED NOT NULL,
    ANSWER INT(6) UNSIGNED NOT NULL,
    FOREIGN KEY (QUESTION) REFERENCES QUESTIONS (QID)
    ON UPDATE NO ACTION ON DELETE NO ACTION,
    FOREIGN KEY (ANSWER) REFERENCES ANSWERS (AID)
    ON UPDATE NO ACTION ON DELETE NO ACTION);
